# -*- coding: utf-8 -*-
"""Age Calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaTXGtzljs_fBm_CXmIJ3rRc8_sVn0nY
"""

# Age Calculator
from datetime import datetime

def calculate_age():
    try:
                # try is the reason if user if not entered the mm/dd/yy format means,
                #it shows the invalid date format
        # Asks user birthdate
        birth_input = input("Enter your birthdate (mm/dd/yyyy): ")

        # Validates the input format
        birth_date = datetime.strptime(birth_input, "%m/%d/%Y")

        # Calculate age
        today = datetime.today() # Get today's date
        age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
        # if (today.month, today.day) < (birth_date.month, birth_date.day):(another logic)
            # age -= 1
        print(f"Your age is: {age} years")

        # Convert to European format
        euro_format = birth_date.strftime("%d/%m/%Y")
        print(f"Your birthdate in European format: {euro_format}")

        # Handelling errors with appropriate messages
    except ValueError:
        print("Invalid date format. Please enter in mm/dd/yyyy format.")

calculate_age()