# -*- coding: utf-8 -*-
"""prime number.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vF6ZY6TbXbc61jVHfJQdNSWgt7sqO3Q8
"""

# Prime Number Generator
def is_prime(n):
    # Function to check if a number is prime
    if n <= 1:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

def generate_primes():
    try:
        # Takes two positive integers as input
        start = int(input("Enter start of range: ")) # start
        end = int(input("Enter end of range: ")) # end

        # Validate input
        if start < 0 or end < 0:
            print("Both numbers must be positive.")
            return

        primes = []

        # Find all primes in range
        for num in range(start, end + 1):
            if is_prime(num):
                primes.append(num)

        # Display primes: 10 numbers per line
        for i in range(0, len(primes), 10):
            print(*primes[i:i+10])

    except ValueError:
        print("Invalid input. Please enter positive integers.")

generate_primes()